name: '${pluginName}'
version: '${version}'
main: org.yuemi.mmoitems.plugin.MmoItemsPlugin
authors: [${authors}]
api-version: '${apiVersion}'

softdepend: [
  YueMiLibs,
  PlaceholderAPI
]

commands:
  mmoitems:
    description: "Main command for MC-MMO-Items"
    aliases: [items]
    permission: mmoitems.admin

